-- CRIACAO OBJETOS BD

--SELECT NAME ,
--    STATUS
--  FROM   V$DATAFILE
--  WHERE STATUS = 'ONLINE';

--CRIANDO TABLESPACE PARA USUÁRIO E TABELAS DA APLICAÇÃO
CREATE TABLESPACE CRUD_CLIENTE_ENDERECO_APP 
DATAFILE 'USERS01.DBF'  
SIZE 10M AUTOEXTEND ON;

--CRIAÇÃO DE USUÁRIO
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER USERAPP IDENTIFIED BY CRUDUSERAPP 
DEFAULT TABLESPACE CRUD_CLIENTE_ENDERECO_APP;

GRANT create session TO USERAPP;
GRANT create table TO USERAPP;
GRANT create view TO USERAPP;
GRANT create any trigger TO USERAPP;
GRANT create any procedure TO USERAPP;
GRANT create sequence TO USERAPP;
GRANT create synonym TO USERAPP;

alter user USERAPP quota unlimited on CRUD_CLIENTE_ENDERECO_APP ;

--CRIANDO AS TABELAS DA APLIAÇÃO

CREATE TABLE USERAPP.TIPODOCUMENTO(
TIPODOCUMENTO_ID    NUMBER(3,0),
DESCRICAO           VARCHAR2(30) NOT NULL,
CONSTRAINT PK_TIPODOCUMENTO PRIMARY KEY (TIPODOCUMENTO_ID));

CREATE TABLE USERAPP.CLIENTE(
CLIENTE_ID          NUMBER(14,0),
NOME                VARCHAR2(100) NOT NULL,
DOCUMENTO           NUMBER(14,0) NOT NULL,
TIPODOCUMENTO_ID    NUMBER(3,0) NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY (CLIENTE_ID),
CONSTRAINT FK_CLIENTE_TIPODOCUMENTO FOREIGN KEY (TIPODOCUMENTO_ID) REFERENCES USERAPP.TIPODOCUMENTO (TIPODOCUMENTO_ID));

CREATE TABLE USERAPP.ENDERECO(
ENDERECO_ID     NUMBER(14,0),
LOGRADOURO      VARCHAR2(100) NOT NULL,
NUMERO          NUMBER(8,0) NOT NULL,
COMPLEMENTO     VARCHAR2(50) NULL,
BAIRRO          VARCHAR2(50) NOT NULL,
UF              VARCHAR2(2) NOT NULL,
CEP             VARCHAR2(9) NULL,
CLIENTE_ID      NUMBER(14,0) NOT NULL,
CONSTRAINT PK_ENDERECO PRIMARY KEY (ENDERECO_ID),
CONSTRAINT FK_ENDERECO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES USERAPP.CLIENTE(CLIENTE_ID));

--CRIANDO SEQUENCES

CREATE SEQUENCE USERAPP.TIPODOCUMENTO_SQ
  MINVALUE 1 START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE USERAPP.CLIENTE_SQ
  MINVALUE 1 START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE USERAPP.ENDERECO_SQ
  MINVALUE 1 START WITH 1 INCREMENT BY 1;

--INSERINDO OS VALORES INICIAIS PARA TIPOS DE DOCUMENTO

INSERT INTO USERAPP.TIPODOCUMENTO(tipodocumento_id, DESCRICAO) 
VALUES (USERAPP.TIPODOCUMENTO_SQ.NEXTVAL, 'CPF');

INSERT INTO USERAPP.TIPODOCUMENTO(tipodocumento_id, DESCRICAO) 
VALUES (USERAPP.TIPODOCUMENTO_SQ.NEXTVAL, 'CNPJ');

COMMIT;        

